# Generated by Django 3.2.13 on 2022-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
